AR = '/usr/bin/ar'
ARFLAGS = 'rcs'
CCFLAGS_MACBUNDLE = ['-fPIC']
CC_VERSION = ('4', '8', '2')
COMPILER_CXX = 'g++'
CPP = '/usr/bin/cpp'
CPPPATH_ST = '-I%s'
CXX = ['/usr/bin/g++']
CXXDEFINES = ['HAVE_CONFIG_H']
CXXDEFINES_ST = '-D%s'
CXXFLAGS = []
CXXFLAGS_DEBUG = ['-g']
CXXFLAGS_GQR = ['-ansi', '-Wall', '-pedantic', '-O3', '-DNDEBUG']
CXXFLAGS_RELEASE = ['-O2']
CXXFLAGS_TESTS = ['-g', '-O3', '-D_GLIBCXX_DEBUG']
CXXLNK_SRC_F = ''
CXXLNK_TGT_F = ['-o', '']
CXX_NAME = 'gcc'
CXX_SRC_F = ''
CXX_TGT_F = ['-c', '-o', '']
DEST_BINFMT = 'elf'
DEST_CPU = 'x86_64'
DEST_OS = 'linux'
FULLSTATIC_MARKER = '-static'
GQR_DEFAULT_DATA_DIR = '/usr/local/share/gqr/data'
GQR_VERSION = '1500'
LIBPATH_ST = '-L%s'
LIB_ST = '-l%s'
LINKFLAGS_GQR-STATIC = '-static'
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINK_CXX = ['/usr/bin/g++']
PREFIX = '/usr/local'
PRG_DOXYGEN_PATH = '/usr/bin/doxygen'
PRG_INSTALL_PATH = '/usr/bin/install'
RANLIB = '/usr/bin/ranlib'
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STATICLIBPATH_ST = '-L%s'
STATICLIB_MARKER = '-Wl,-Bstatic'
STATICLIB_ST = '-l%s'
cfg_files = ['gqr/config.h']
defines = {'GQR_DEFAULT_DATA_DIR': '"/usr/local/share/gqr/data"'}
macbundle_PATTERN = '%s.bundle'
program_PATTERN = '%s'
shlib_CXXFLAGS = ['-fPIC', '-DPIC']
shlib_LINKFLAGS = ['-shared']
shlib_PATTERN = 'lib%s.so'
staticlib_LINKFLAGS = ['-Wl,-Bstatic']
staticlib_PATTERN = 'lib%s.a'
